name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v2
